# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # https://github.com/AndrewDryga/vagrant-box-osx
  #config.vm.box = "osx-yosemite"
  config.vm.box = "http://files.dryga.com/boxes/osx-yosemite-0.2.0.box"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.box_check_update = false
  config.ssh.forward_agent = true
  config.ssh.insert_key = false

  #config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"
  #config.vm.synced_folder ".", "/vagrant", :nfs => { :mount_options => ["dmode=777","fmode=777"] }

  config.vm.provider "virtualbox" do |vb|
    # Do/don't boot with headless mode
    vb.gui = true

    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    # This should speed up compilation times
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    # Necessary to use multiple CPUs
    vb.customize ["modifyvm", :id, "--ioapic", "on"]

    ### OSX guest specific settings
    #vb.customize ["modifyvm", :id, "--cpuidset", "00000001","000206a7","02100800","1fbae3bf","bfebfbff"] # get OSX to boot past "hfs ..." message
    vb.customize ["modifyvm", :id, "--cpuidset", "00000001","000306a9","00020800","80000201","178bfbff"] # boot past "Missing Bluetooth Controller Transport" error
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct", "MacBookPro11,3"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion", "1.0"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct", "Iloveapple"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/smc/0/Config/DeviceKey", "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"]
    vb.customize ["setextradata", :id, "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC", "1"]

    # set resolution on OSX:
    # 0,1,2,3,4,5 :: 640x480, 800x600, 1024x768, 1280x1024, 1440x900, 1920x1200
    vb.customize ["setextradata", :id, "VBoxInternal2/EfiGopMode", "2"]

    # Provisioning
	config.vm.provision "shell", privileged: false, path: "provision.sh"
  end

end
